- name: Deploy Staging
  if: ${{ github.ref == 'refs/heads/dev' }}
  uses: superfly/flyctl-actions@1.3
  with:
    args: "deploy --app ${{ env.APP_NAME }}-staging --image registry.fly.io/${{ env.APP_NAME }}:${{ github.sha }}"
  env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
